// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

import "fmt"

func PrintString(value string) {
	fmt.Printf("%#v", value)
}

func callPrintString(value string) {
	var v string
	PrintString(v)
}

func PrintInt(value int) {
	fmt.Printf("%#v", value)
}

func callPrintInt(value int) {
	var v int
	PrintInt(v)
}
